name: hifiasm
description: Run de novo genome assembly wiith hifiasm based on PacBio HiFi reads
keywords:
  - genome assembly
  - pacbaio
  - hifi reads
  - consensus reads
  - long reads
  - fastq
tools:
  - hifiasm:
      description: Haplotype-resolved assembler for accurate HiFi reads
      homepage: https://github.com/chhylp123/hifiasm
      documentation: https://github.com/chhylp123/hifiasm
      tool_dev_url: https://github.com/chhylp123/hifiasm
      doi: "10.1038/s41592-020-01056-5"
      licence: ['MIT']

## TODO nf-core: Add a description of all of the variables used as input
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  ## TODO nf-core: Delete / customise this example input
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  ## TODO nf-core: Delete / customise this example output
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

authors:
  - "@sidorov-si"
