name: hifiasm
description: Run hifiasm on Pacbio HiFi reads
keywords:
    - genome assembly
    - pacbaio
    - hifi
    - long reads
    - fastq
tools:
    - hifiasm:
        description: |
            hifiasm generates a genome assembly from long Pacbio HiFi reads. ...Haplotype resolution ...Using short reads.
        homepage: https://github.com/chhylp123/hifiasm
        documentation: https://github.com/chhylp123/hifiasm
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
            List of input FastQ files of size 1 and 2 for single-end and paired-end data,
            respectively.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - html:
        type: file
        description: FastQC report
        pattern: "*_{fastqc.html}"
    - zip:
        type: file
        description: FastQC report archive
        pattern: "*_{fastqc.zip}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@drpatelh"
    - "@grst"
    - "@ewels"
    - "@FelixKrueger"
