name: augustus_augustus
description: This process finds genes in a nucleotide FASTA file using an AUGUSTUS gene prediction model. The inputs are a nucleotide FASTA file to search and an AUGUSTUS model. The model will be the output of one of AUGUSTUS_COPYMODEL, AUGUSTUS_PRETRAINED, or AUGUSTUS_OPTIMIZE, as these processes output the model in a Nextflow-friendly channel-wise manner.
keywords:
  - AUGUSTUS
  - gene prediction
  - annotation
tools:
  - augustus:
      description: AUGUSTUS is a gene prediction program for eukaryotes written by Mario Stanke and Oliver Keller. It can be used as an ab initio program, which means it bases its prediction purely on the sequence. AUGUSTUS may also incorporate hints on the gene structure coming from extrinsic sources such as EST, MS/MS, protein alignments and synthenic genomic alignments.
      homepage: http://bioinf.uni-greifswald.de/augustus/
      documentation: https://github.com/Gaius-Augustus/Augustus
      tool_dev_url: https://github.com/Gaius-Augustus/Augustus
      doi: "10.1093/bioinformatics/btn013"
      licence: ['Artistic Licence']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A nucleotide FASTA to search for genes.
      pattern: "*{.fa,.fna,.fasta}"
  - augustus_model:
      type: directory
      description: A directory containing an AUGUSTUS gene prediction model.
  - species:
      type: string
      description: A string with a species name. In reality, this is a subdirectory in AUGUSTUS_CONFIG_PATH/config/species/.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
  - gff:
      type: file
      description: A file containing gene models predicted by the AUGUSTUS model.
      pattern: "*{.gff,.gff3}"

authors:
  - "@mjmansfi"
