# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nfcore-star-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages
  - pigz=2.3.4

  ## bioconda packages, see above
  - star=2.7.3a