name: augustus_bam2hints
description: This process extracts AUGUSTUS gene hints, that is, intron structures, out of a sorted BAM file and outputs the hints in GFF format.
keywords:
  - AUGUSTUS
  - gene prediction
  - annotation
tools:
  - augustus:
      description: AUGUSTUS is a gene prediction program for eukaryotes written by Mario Stanke and Oliver Keller. It can be used as an ab initio program, which means it bases its prediction purely on the sequence. AUGUSTUS may also incorporate hints on the gene structure coming from extrinsic sources such as EST, MS/MS, protein alignments and synthenic genomic alignments.
      homepage: http://bioinf.uni-greifswald.de/augustus/
      documentation: https://github.com/Gaius-Augustus/Augustus
      tool_dev_url: https://github.com/Gaius-Augustus/Augustus
      doi: "10.1093/bioinformatics/btn013"
      licence: ['Artistic Licence']

input:
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam}"

output:
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - gff:
      type: file
      description: A GFF file containing gene hints - by default, only the introns - for training an AUGUSTUS gene model predictor.
      pattern: "*.{gff, gff3}"

authors:
  - "@mjmansfi"
