name: augustus_newspecies
description: This process takes a species name as a string and initiates a new AUGUSTUS model (a directory). It outputs the AUGUSTUS model in a standardized output channel format for use with the AUGUSTUS_AUGUSTUS gene prediction process.
keywords:
  - AUGUSTUS
  - gene prediction
  - annotation
tools:
  - augustus:
      description: AUGUSTUS is a gene prediction program for eukaryotes written by Mario Stanke and Oliver Keller. It can be used as an ab initio program, which means it bases its prediction purely on the sequence. AUGUSTUS may also incorporate hints on the gene structure coming from extrinsic sources such as EST, MS/MS, protein alignments and synthenic genomic alignments.
      homepage: http://bioinf.uni-greifswald.de/augustus/
      documentation: https://github.com/Gaius-Augustus/Augustus
      tool_dev_url: https://github.com/Gaius-Augustus/Augustus
      doi: "10.1093/bioinformatics/btn013"
      licence: ['Artistic Licence']

input:
  - species:
      type: string
      description: A string with a species name. In reality, this is a subdirectory in AUGUSTUS_CONFIG_PATH/config/species/.

output:
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - augustus_model:
      type: directory
      description: A directory containing an AUGUSTUS gene prediction model.
  - species:
      type: string
      description: A string with a species name. In reality, this is a subdirectory in AUGUSTUS_CONFIG_PATH/config/species/.

authors:
  - "@mjmansfi"
