name: augustus_filter
description: This process takes a user-provided, pre-trained AUGUSTUS model (a directory) as well as a species name. It outputs the AUGUSTUS model in a standardized output channel format for use with the AUGUSTUS_AUGUSTUS gene prediction process.
keywords:
  - AUGUSTUS
  - gene prediction
  - annotation
tools:
  - augustus:
      description: AUGUSTUS is a gene prediction program for eukaryotes written by Mario Stanke and Oliver Keller. It can be used as an ab initio program, which means it bases its prediction purely on the sequence. AUGUSTUS may also incorporate hints on the gene structure coming from extrinsic sources such as EST, MS/MS, protein alignments and synthenic genomic alignments.
      homepage: http://bioinf.uni-greifswald.de/augustus/
      documentation: https://github.com/Gaius-Augustus/Augustus
      tool_dev_url: https://github.com/Gaius-Augustus/Augustus
      doi: "10.1093/bioinformatics/btn013"
      licence: ['Artistic Licence']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - genbank:
      type: file
      description: A genbank file used to train an AUGUSTUS model.
  - model_txt:
      type: path
      description: A file containing the text output of an AUGUSTUS etraining run. Needed to filter out
      pattern: "*.model.txt"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - genbank:
      type: file
      description: A filtered genbank file, with AUGUSTUS-flagged bad genes removed.
      pattern: "*{.gb,.gbk,.genbank}"

authors:
  - "@mjmansfi"
