name: augustus_gff2gb
description: This process turns a GFF or GTF file into a Genbank format file suitably formatted for AUGUSTUS. The inputs are meta/fasta tuple, a GTF or GFF file, and a value for gene flanking size.
keywords:
  - AUGUSTUS
  - gene prediction
  - annotation
tools:
  - augustus:
      description: AUGUSTUS is a gene prediction program for eukaryotes written by Mario Stanke and Oliver Keller. It can be used as an ab initio program, which means it bases its prediction purely on the sequence. AUGUSTUS may also incorporate hints on the gene structure coming from extrinsic sources such as EST, MS/MS, protein alignments and synthenic genomic alignments.
      homepage: http://bioinf.uni-greifswald.de/augustus/
      documentation: https://github.com/Gaius-Augustus/Augustus
      tool_dev_url: https://github.com/Gaius-Augustus/Augustus
      doi: "10.1093/bioinformatics/btn013"
      licence: ['Artistic Licence']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A nucleotide FASTA file.
      pattern: "*{.fa,.fna,.fasta}"
  - gxf:
      type: file
      description: A GTF or GFF file containing gene annotations.
  - flanking_size:
      type: integer
      description: The size for flanking regions around gene annotations.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
  - genbank:
      type: file
      description: A genbank file containing gene annotations, converted from a GTF or GFF file.
      pattern: "*{.gff,.gff3}"

authors:
  - "@mjmansfi"
