name: augustus_split
description: This input to this process is a genbank file containing gene models for training an AUGUSTUS model, typically the output of AUGUSTUS_FILTER. The input is split into two output genbank files for training and testing AUGUSTUS gene prediction models.
keywords:
  - AUGUSTUS
  - gene prediction
  - annotation
tools:
  - augustus:
      description: AUGUSTUS is a gene prediction program for eukaryotes written by Mario Stanke and Oliver Keller. It can be used as an ab initio program, which means it bases its prediction purely on the sequence. AUGUSTUS may also incorporate hints on the gene structure coming from extrinsic sources such as EST, MS/MS, protein alignments and synthenic genomic alignments.
      homepage: http://bioinf.uni-greifswald.de/augustus/
      documentation: https://github.com/Gaius-Augustus/Augustus
      tool_dev_url: https://github.com/Gaius-Augustus/Augustus
      doi: "10.1093/bioinformatics/btn013"
      licence: ['Artistic Licence']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - genbank:
      type: file
      description: A genbank file used to train an AUGUSTUS model. Typically this is the output of AUGUSTUS_FILTER.
      pattern: "*{.gb,.gbk,.genbank}"
  - split_size:
      type: integer
      description: A value specifying the split size for splitting training and test sets. The AUGUSTUS authors recommend a default of 200.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - train_genbank:
      type: file
      description: A subsetted genbank file for training an AUGUSTUS gene prediction model.
      pattern: "*{.gb,.gbk,.genbank}"
  - test_genbank:
      type: file
      description: A subsetted genbank file for testing an AUGUSTUS gene prediction model.
      pattern: "*{.gb,.gbk,.genbank}"

authors:
  - "@mjmansfi"
